# Generated by Django 4.1.7 on 2023-03-12 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actType', models.CharField(choices=[('0', 'Lecture'), ('1', 'Workshop'), ('3', 'Conference'), ('4', 'Thon')], default='0', max_length=1)),
                ('title', models.CharField(max_length=150, null=True)),
                ('actImage', models.ImageField(upload_to='event/', verbose_name='Event Image')),
                ('content', tinymce.models.HTMLField(null=True)),
                ('place', models.CharField(choices=[('0', 'Online'), ('1', 'Local')], default='0', max_length=1)),
                ('location', tinymce.models.HTMLField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('actDate', models.DateField(null=True)),
                ('actTime', models.TimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attend', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
