# Generated by Django 4.1.7 on 2023-03-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activity_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='status',
            new_name='statusEnd',
        ),
        migrations.AddField(
            model_name='attend',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
